### PR TITLE
Update banner

### PR DESCRIPTION
**Pull request by creativecreatorormaybenot**
## Description

Updates the banner to account for the dark side - I mean dark mode users :)

### CODE REVIEW

**Comment by IchordeDionysos** [comment]
Hmm, maybe some rounded edges would be helpful and maybe a bit more transparency?
image

**Comment by creativecreatorormaybenot** [comment]
@IchordeDionysos will do in a few

**Comment by IchordeDionysos** [comment]
@creativecreatorormaybenot @tomkuschka did create a template for this and re-created this header?

What do you think? :) 
image

**Comment by creativecreatorormaybenot** [comment]
@IchordeDionysos can you share?

**Comment by IchordeDionysos** [comment]
The template?

**Comment by creativecreatorormaybenot** [comment]
No the fish.

**Comment by IchordeDionysos** [comment]
Yes, will send it to you tomorrow: :)

**Comment by creativecreatorormaybenot** [comment]
What was the reason for creating a new one? About what you asked: I think the old version is better because it uses the space better. Especially because I am using the same thing for the social media preview which does not work with the new version I guess.

**Comment by IchordeDionysos** [comment]
To streamline it with the new UX and to make it easier for everyone to use the template without the need to have access to Photoshop.
We will have the template in XD along with all the rest of our design library :)

**Comment by creativecreatorormaybenot** [comment]
OK, I updated it to use my bigger design now to match the social media preview 👍 We can think about aligning this one later but this should work for now.

**Pull request merged**
