### PR TITLE
Bumped Petitparser Version

### PR DESCRIPTION
**Pull request by garv-shah**
## Description

Bumps the version of a dependency, petitparser

## Related issues & PRs

Fix to https://github.com/simpleclub/math_keyboard/issues/35

[keywords]: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

## Checklist

- [x] I have made myself familiar with the CaTeX
      [contributing guide](https://github.com/simpleclub/math_keyboard/blob/master/CONTRIBUTING.md).
- [x] I added a PR description.
- [x] I linked all related issues and PRs I could find (no links if there are none).
- [x] If this PR changes anything about the main `math_keyboard` or `example` package
      (also README etc.), I created an entry in `CHANGELOG.md` (`## UPCOMING RELEASE` if the change
      on its own is not worth an update).
- [x] All required checks pass.

### CODE REVIEW

**Review by edhom — APPROVED** [review]
LGTM. Thanks for contributing🙏

**Comment by edhom** [comment]
@garv-shah Ah can you open a new PR with signed commits? Or you want me to create it?😄

**Comment by garv-shah** [comment]
oh, sorry, sure, i'll try!

**Comment by garv-shah** [comment]
Does this work or would I have to create a new PR? Sorry haha, I have no clue how signed commits work

**Comment by edhom** [comment]
@garv-shah Should work! You just need to upload your gpg key on GitHub I think🙂

**Comment by garv-shah** [comment]
oh alright!

**Comment by garv-shah** [comment]
done!

**Review by edhom — APPROVED** [review]

**Comment by garv-shah** [comment]
Thank you!

**Pull request merged**
